name: Plumber

on:
  push:
    branches: [stage, main]
  pull_request:
    branches: [stage]
  workflow_dispatch: null

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  plumber:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: getplumber/plumber@c85c712bca3c9f547a88c66bb2541db179a1a79e # v0.4.12, 2026-07-20
        with:
          score-push: true
